### ISSUE TITLE
Batch uploads to GCS in case of tars with large number of files

### ISSUE THREAD

**Issue by wkillerud** [eik-lib/core#419]
From https://github.com/eik-lib/sink-gcs/pull/263

> When the tar file is extracted on the server, each file inside the tar file if written to GCS: https://github.com/eik-lib/core/blob/master/lib/multipart/parser.js#L129
> 300 files in a tar file will open 300 write streams to GCS. It might be that we should apply a proper queue to control and batch these write streams instead of firing off 300 at once. https://github.com/eik-lib/core/blob/master/lib/multipart/parser.js#L129

**Comment by wkillerud** [comment]
I suppose the problem is that in the real scenario what is resolved is a connection/stream to GCS, not a finished file upload.

**Comment by wkillerud** [comment]
Problem: 
- the `tar` stream moves forward as soon as we pipe the entry to a writable stream (ex. the response from Google Cloud Storage's `createWriteStream`).
- because of this we end up with a large amount of concurrent connections if the `tar` has many files (creating a writable stream is faster than completing an upload).
- we want to avoid storing all the file's contents in memory or on disk.

Questions:
- Can we throttle `tar` so it doesn't move on to the next entry until a stream later in the pipeline is finished?
- Can we design the `async write` function for GCS so it doesn't resolve if there are N number of active streams?

**Comment by trygve-lie** [comment]
> the tar stream moves forward as soon as we pipe the entry to a writable stream (ex. the response from Google Cloud Storage's createWriteStream).
because of this we end up with a large amount of concurrent connections if the tar has many files (creating a writable stream is faster than completing an upload).

I'm not sure we do end up with a lot of concurrent connections. From [tar.Parse()](https://github.com/isaacs/node-tar?tab=readme-ov-file#class-tarparse):

> Each entry will not emit until the one before it is flushed through, so make sure to either consume the data (with on('data', ...) or .pipe(...)) or throw it away with .resume() to keep the stream flowing.

I think we get one connection after each other due to tar not emitting a new file before the previous is fully consumed (flushed through). It looks like that is whats happening in the result of your test too.

**Comment by wkillerud** [comment]
> It looks like that is whats happening in the result of your test too.

I thought the upload is done only when the callback to the `pipeline(entry, writable` etc is run, logging `PERSISTED <filename>`. I get a bunch of those at the end, which makes me think that is an issue.

**Comment by trygve-lie** [comment]
> I thought the upload is done only when the callback to the pipeline(entry, writable etc is run, logging PERSISTED <filename>. I get a bunch of those at the end, which makes me think that is an issue.

The tar file upload and extraction itself is done when the callback on the pipeline executes. Though; For each file in the tar file there is a `entry` there is created a stream which writes the files to the GCS bucket. These happen after each other, not in parallel so we are not getting concurrent writes to the bucket. They are in sequence.

Each `entry` is pushed to an queue array which is resolved with a `Promise.all` in the callback to the pipeline of the extraction of the tar. My hunch is that all the promises in the `Promise.all` is already resolved when that `Promise.all` is executed. Which make me question if its needed atm.

I can't recall exactly why its like this, but it might be that `tar.Parse()` did not wait until each entry was consumed before. Iow; in an earlier version of tar we got a bunch of concurrent entry streams. Then the `Promise.all` make sense.

I am not convinced this is the issue though.
