### ISSUE TITLE
Extract the file system sink to its own module

### ISSUE THREAD

**Issue by wkillerud** [eik-lib/core#427]
The current API to configure the file system sink is based on environment variables (`SINK_PATH` and `SINK_TYPE`). As an end user it would be nice to be able to import and instantiate the file system sink similar to how the sink for Google Cloud Storage works.

We could still keep the file system and memory sinks as built-ins with today's API surface for backwards compatibility. `core` would depend on and import `@eik/sink-file-system` and `@eik/sink-memory` rather than keeping the sink implementations private.

**Comment by wkillerud** [comment]
I made https://github.com/eik-lib/sink-memory last week not knowing about these built-ins 😅

**Comment by leftieFriele** [comment]
I think this is a good idea, bringing all sink to be implemented in the same way.

**Comment by wkillerud** [comment]
https://github.com/eik-lib/sink-file-system
