### ISSUE TITLE
Only latest version shows in versions array

### ISSUE THREAD

**Issue by digitalsadhu** [eik-lib/core#71]
When I visit `http://localhost:4001/map/my-map-test`, only the latest version shows up in the array.

```json
{
  "versions": [
    [
      1,
      {
        "version": "1.0.2",
        "integrity": "sha512-hTa+HaZLSjhw4kpAs4ojrXB0NRXQ4JG7LnanLWfB8GizW/MUpu8n5raaUNZ6dUWme9aZCy+Cis9ymYIjWdcsJQ=="
      }
    ]
  ],
  "name": "my-map-test",
  "org": "finn"
}
```

Visiting `http://local.finn.no:4001/finn/map/my-map-test/1.0.0` and `http://local.finn.no:4001/finn/map/my-map-test/1.0.1` and `http://local.finn.no:4001/finn/map/my-map-test/1.0.2` all work, however.

The same applies for `pkg` endpoints

**Comment by trygve-lie** [comment]
Yeah. It lists only the latest version of a major. Do we have a use case for getting all versions as is?

**Comment by digitalsadhu** [comment]
Ah ok, intended then. My only use case was being able to list all versions in a `npm show` style command at some point. Theres currently no way to know what's been published.
